### ISSUE TITLE
Can not download datasets from Dropbox

### ISSUE THREAD

**Issue by ChenCyril** [icedpanda/KERL#1]
Hi, I have some problems to download datasets from Dropbox. I have sign in Dropbox and it tells me that I can not access the files.
So, could you upload the dataset file to Google Cloud so that it can be easily downloaded?
Thanks,

**Comment by icedpanda** [comment]
Thanks for bringing this up. The model weights are now on Goold Drive. You can find the update in 7d63606ad8698f713091b09f5ac90e697117acf9.
