### ISSUE TITLE
24G显存不足

### ISSUE THREAD

**Issue by ayin121024** [icedpanda/KERL#3]
作者你好，我按照您的配置使用了24G带2颗GPU的服务器来训练模型，一段时间后显存占用过高，无法继续运行，然后我换了更高配置的服务器重新尝试，一样的结果，随着运行的时间显存占用也在增长，直到无法继续运行而报错。此外，我减少了批次的大小依旧失败。请问一下这个问题我应该如何解决？

**Comment by icedpanda** [comment]
Duplicate of #4. Closing this.
